Update stickers from sticker packs in runtime
reijo1337/ToxicBot pull request #19
Opened 2022-08-31 12:39 UTC by Dimama

2022-08-31 12:44 UTC, FuryJohnson commented on README.md
> +* `STICKERS_UPDATE_INTERVAL` - Интервал обновления стикеров из заданных стикер паков. По умолчанию `600s`
Почему 600? Откуда был взят этот интервал?

2022-08-31 12:44 UTC, FuryJohnson commented on cmd/main.go
> +	StickersUpdateInterval	time.Duration `envconfig:"STICKERS_UPDATE_INTERVAL" default:"600s"`
Вопрос про 600s остается открытым и здесь :)

2022-08-31 12:44 UTC, FuryJohnson commented on cmd/main.go
> +	stickersReactionHandler, err := on_sticker.New(b, cfg.StickerSets, logger)
аргумент b, на мой взгляд, неочевиден, что он в себе несет?

2022-08-31 12:44 UTC, FuryJohnson commented on cmd/main.go
> +					logger.WithError(err).Warn("can't get stickers from sticker packs")
Данный кусок кода надо бы отформатировать

2022-09-17 13:18 UTC, reijo1337 requested changes
Все хорошо, только управление списком стикеров нужно сделать в одном месте
Сейчас оно размазано по хендлеру и мейну

2022-09-17 13:18 UTC, reijo1337 commented on cmd/main.go
> +				err = stickersReactionHandler.UpdateStickersFromPacks(b)
Данную функциональность лучше вынести в отдельную сущность, которая будет хранить и обновлять стикеры
Прекращение обновлений можно сделать через ctx.Done(), контекст передавать в функцию-конструктор

2022-09-17 13:18 UTC, reijo1337 commented on cmd/main.go
> +	stickersUpdateDone <- struct{}{}
Обычно такие штуки оформляются через закрытие канала 
Кстати по сути это дубль канала done

2022-09-17 13:18 UTC, reijo1337 commented on internal/handlers/on_sticker/sticker_reactions.go
> +	sr.mu.Lock()
Тут должен быть RLock

2022-09-17 13:20 UTC, reijo1337 commented on README.md
> +* `STICKERS_UPDATE_INTERVAL` - Интервал обновления стикеров из заданных стикер паков. По умолчанию `600s`
Это дефолтное значение настраиваемого параметра, чисто субъективно, чаще чем раз в 10 минут стикеры обновляться не будут
Но и ждать по часу/дню/недели обновления не хочется

2022-09-17 13:21 UTC, reijo1337 commented on cmd/main.go
> +	stickersReactionHandler, err := on_sticker.New(b, cfg.StickerSets, logger)
Попробуй почитать всю функцию целиком. Смысл переменной в контексте данной функции понятен.

2022-09-17 14:18 UTC, reijo1337 commented on cmd/main.go
> +				err = stickersReactionHandler.UpdateStickersFromPacks(b)
Либо это еще лучше сделать через функцию Close, вызов которой можно обернуть через defer в мейне

2026-04-25 00:44 UTC, closed without merging