add google storage
reijo1337/ToxicBot pull request #20
Opened 2022-11-06 17:21 UTC by Pacman29

2022-11-07 10:05 UTC, reijo1337 commented on internal/google_spreadsheet/google_spreadsheets.go
> +	googleClient.client = googleClient.configJwt.Client(ctx)
тут прокидывается context.Background(), а он не должен закрываться по завершению программы?

2022-11-07 10:07 UTC, reijo1337 commented on internal/handlers/on_sticker/updater.go
> +		case <-ctx.Done():
https://github.com/reijo1337/ToxicBot/pull/20/files?diff=split&w=0#diff-c444f711e9191b53952edb65bfd8c644419fc7695c62611dc0fb304b4fb197d6R33
этот case никогда не произойдет

2022-11-07 10:13 UTC, reijo1337 requested changes
Везде прокидывается context.Background(), но зависимости ожидают что он когда-то завершится

2022-11-07 10:28 UTC, reijo1337 commented on internal/handlers/on_sticker/sticker_reactions.go
> +		stickersFromPacks: stickersFromPacks,
зачем разносить стикеры из паков и синкующиеся стикеры в разные поля?

2022-11-07 10:29 UTC, reijo1337 commented on internal/handlers/on_text/bulling/bulling.go
> +	storage storage.Manager
ты прогонял такое расположение полей через утилизацию памяти? иначе я не могу понять зачем в разнобой они так добавлены

2022-11-07 10:31 UTC, reijo1337 commented on internal/handlers/on_user_join/greetings.go
> +	cfg config
алсо, такой же вопрос, в чем смысл такого порядка добавления новых полей?

2022-11-07 10:32 UTC, reijo1337 commented on internal/handlers/on_user_join/greetings.go
> +	cfg config
вижу только что они указаны в алфавитном порядке

2022-11-07 10:34 UTC, reijo1337 commented on internal/handlers/on_voice/updater.go
> +	stickers := make([]string, 0, len(r))
voices

2022-11-07 10:34 UTC, reijo1337 commented on internal/utils/bot_utils.go
> +func GetStickersFromPacks(bot *telebot.Bot, stickerPacksNames []string) ([]string, error) {
почему паки не вынес в бд?

2022-11-07 11:30 UTC, Pacman29 commented on internal/handlers/on_sticker/sticker_reactions.go
> +		stickersFromPacks: stickersFromPacks,
У меня нет доступа до них, и кажется @Dimama хотел их сам правильно на бд унести, пока переделываем тот код что есть сейчас, а сейчас они из 2х мест

2022-11-07 11:35 UTC, Pacman29 commented on internal/handlers/on_text/bulling/bulling.go
> +	storage storage.Manager
Нет не прогонял, так как тут линтера нет.

2022-11-07 11:35 UTC, Pacman29 commented on internal/handlers/on_user_join/greetings.go
> +	cfg config
угу, как бы надо добавить линтер и проверить через него с учетом аллокаций, но кажется это можно отдельным пр сделать

2022-11-07 11:35 UTC, Pacman29 commented on internal/utils/bot_utils.go
> +func GetStickersFromPacks(bot *telebot.Bot, stickerPacksNames []string) ([]string, error) {
Так как они в енвах, доступа до них нет

2022-11-18 17:27 UTC, reijo1337 approved these changes

2022-11-25 14:15 UTC, merged